//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GREWords
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORD
    {
        public int ID { get; set; }
        public string WORD1 { get; set; }
        public string WORDTYPE { get; set; }
        public string MEANING { get; set; }
        public string EXAMPLE { get; set; }
    }
}
